import React from 'react'
import JobCard from '../jobsComponents/JobCard'
import mac from "../../assets/mac.png";
import WhatsApp from "../../assets/WhatsApp.jpg";
import apple from "../../assets/apple.jpg";

function CompanyJobOffers() {
    const jobs = [
        {
            id: 1,
            title: "Customer Service Representative",
            companyName: "McDonald's",
            date_posted: "2024-01-18",
            date_delais: "2024-02-18",
            offer_status: "Open",
            job_type: "Full-time",
            salary: "$15",
            pay_period: "hr",
            description: "Join the McDonald's team as a Customer Service Representative and be a part of the world's leading fast-food restaurant chain. At McDonald's, we are committed to providing exceptional service and creating a positive dining experience for our customers.\n\nAs a Customer Service Representative, you will play a crucial role in ensuring customer satisfaction by taking orders, processing payments, and providing friendly assistance. This position offers a dynamic and fast-paced work environment, making it an ideal opportunity for individuals who thrive in customer-focused roles.\n\nResponsibilities:\n- Greet customers and provide a warm welcome.\n- Take and process customer orders accurately and efficiently.\n- Handle cash transactions and operate the point-of-sale system.\n- Maintain cleanliness and organization in the dining area.\n- Address customer inquiries and resolve issues promptly.\n- Collaborate with team members to ensure smooth operations.\n\nQualifications:\n- Previous experience in customer service is a plus.\n- Excellent communication and interpersonal skills.\n- Ability to work in a fast-paced environment.\n- Flexibility to work various shifts, including evenings and weekends.\n- Enthusiastic and positive attitude.\n\nJoin the McDonald's family and contribute to our commitment to quality, service, and cleanliness. If you are passionate about delivering excellent customer service and enjoy working in a team-oriented atmosphere, we invite you to apply for this exciting opportunity.\n\nApply now and become a valuable member of the McDonald's team!",
            country: "United States",
            city: "New York",
            photo: mac,
        },
        {
            id: 2,
            title: "Technical Support Specialist",
            companyName: "Apple Inc.",
            date_posted: "2024-01-20",
            date_delais: "2024-02-20",
            offer_status: "close",
            job_type: "Full-time",
            salary: "$3000",
            pay_period: "mth",
            description: "Join Apple Inc., a global leader in technology and innovation, as a Technical Support Specialist. At Apple, we are dedicated to creating groundbreaking products and providing unparalleled customer support. As a Technical Support Specialist, you will have the opportunity to be part of a team that ensures our customers receive world-class technical assistance.\n\nResponsibilities:\n- Provide technical support to customers via phone, chat, or email.\n- Diagnose and troubleshoot hardware and software issues on Apple products.\n- Collaborate with cross-functional teams to resolve complex technical problems.\n- Educate customers on the use of Apple products and software.\n- Document and escalate issues as needed.\n- Stay informed about the latest Apple products and technologies.\n\nQualifications:\n- Bachelor's degree in a relevant technical field.\n- Proven experience in technical support or a similar role.\n- Strong knowledge of Apple products, macOS, iOS, and related technologies.\n- Excellent communication and problem-solving skills.\n- Ability to work in a fast-paced and dynamic environment.\n- Apple Certified Support Professional (ACSP) certification is a plus.\n\nJoin the Apple team and be a part of transforming the way people live through innovative technology. If you are passionate about technology, customer service, and making a difference, we encourage you to apply for this exciting opportunity.\n\nApply now and contribute to the legacy of innovation at Apple Inc.!",
            country: "United States",
            city: "Cupertino",
            photo: apple,
        },
        {
            id: 3,
            title: "Software Engineer - Messaging Platform",
            companyName: "WhatsApp Inc.",
            date_posted: "2024-01-22",
            date_delais: "2024-02-22",
            offer_status: "close",
            job_type: "Full-time",
            salary: "$89,500",
            pay_period: "year",
            description: "WhatsApp Inc., a leading messaging platform, is seeking a talented Software Engineer to join our Messaging Platform team. As part of the WhatsApp family, you will contribute to building and enhancing one of the most widely used communication platforms globally.\n\nAs a Software Engineer on the Messaging Platform team, you will be involved in designing and implementing features that shape the future of messaging. Join us in creating seamless and secure communication experiences for millions of users worldwide.\n\nResponsibilities:\n- Design, develop, and maintain features for the WhatsApp messaging platform.\n- Collaborate with cross-functional teams to implement scalable and efficient solutions.\n- Optimize performance and troubleshoot issues to ensure a smooth user experience.\n- Stay abreast of industry trends and emerging technologies.\n- Contribute to the overall architecture and design of the messaging platform.\n\nQualifications:\n- Bachelor's degree in Computer Science or a related field.\n- Proven experience as a Software Engineer, with a focus on scalable systems.\n- Proficiency in programming languages such as Java, Kotlin, or C++.\n- Strong understanding of distributed systems and messaging protocols.\n- Experience with mobile application development is a plus.\n\nJoin WhatsApp Inc. and be a part of revolutionizing the way people connect through messaging. If you are passionate about software engineering and excited about shaping the future of communication, we invite you to apply for this exceptional opportunity.\n\nApply now and contribute to the next chapter of innovation at WhatsApp Inc.!",
            country: "United States",
            city: "Menlo Park",
            photo: WhatsApp
        },
        {
            id: 4,
            title: "Technical Support Specialist",
            companyName: "Apple Inc.",
            date_posted: "2024-01-20",
            date_delais: "2024-02-20",
            offer_status: "Open",
            job_type: "Full-time",
            salary: "$3000",
            pay_period: "mth",
            description: "Join Apple Inc., a global leader in technology and innovation, as a Technical Support Specialist. At Apple, we are dedicated to creating groundbreaking products and providing unparalleled customer support. As a Technical Support Specialist, you will have the opportunity to be part of a team that ensures our customers receive world-class technical assistance.\n\nResponsibilities:\n- Provide technical support to customers via phone, chat, or email.\n- Diagnose and troubleshoot hardware and software issues on Apple products.\n- Collaborate with cross-functional teams to resolve complex technical problems.\n- Educate customers on the use of Apple products and software.\n- Document and escalate issues as needed.\n- Stay informed about the latest Apple products and technologies.\n\nQualifications:\n- Bachelor's degree in a relevant technical field.\n- Proven experience in technical support or a similar role.\n- Strong knowledge of Apple products, macOS, iOS, and related technologies.\n- Excellent communication and problem-solving skills.\n- Ability to work in a fast-paced and dynamic environment.\n- Apple Certified Support Professional (ACSP) certification is a plus.\n\nJoin the Apple team and be a part of transforming the way people live through innovative technology. If you are passionate about technology, customer service, and making a difference, we encourage you to apply for this exciting opportunity.\n\nApply now and contribute to the legacy of innovation at Apple Inc.!",
            country: "United States",
            city: "Cupertino",
            photo: apple,
        },

        {
            id: 5,
            title: "Customer Service Representative",
            companyName: "McDonald's",
            date_posted: "2024-01-18",
            date_delais: "2024-02-18",
            offer_status: "Open",
            job_type: "Full-time",
            salary: "$15",
            pay_period: "hr",
            description: "Join the McDonald's team as a Customer Service Representative and be a part of the world's leading fast-food restaurant chain. At McDonald's, we are committed to providing exceptional service and creating a positive dining experience for our customers.\n\nAs a Customer Service Representative, you will play a crucial role in ensuring customer satisfaction by taking orders, processing payments, and providing friendly assistance. This position offers a dynamic and fast-paced work environment, making it an ideal opportunity for individuals who thrive in customer-focused roles.\n\nResponsibilities:\n- Greet customers and provide a warm welcome.\n- Take and process customer orders accurately and efficiently.\n- Handle cash transactions and operate the point-of-sale system.\n- Maintain cleanliness and organization in the dining area.\n- Address customer inquiries and resolve issues promptly.\n- Collaborate with team members to ensure smooth operations.\n\nQualifications:\n- Previous experience in customer service is a plus.\n- Excellent communication and interpersonal skills.\n- Ability to work in a fast-paced environment.\n- Flexibility to work various shifts, including evenings and weekends.\n- Enthusiastic and positive attitude.\n\nJoin the McDonald's family and contribute to our commitment to quality, service, and cleanliness. If you are passionate about delivering excellent customer service and enjoy working in a team-oriented atmosphere, we invite you to apply for this exciting opportunity.\n\nApply now and become a valuable member of the McDonald's team!",
            country: "United States",
            city: "New York",
            photo: mac,
        },
        {
            id: 6,
            title: "Software Engineer - Messaging Platform",
            companyName: "WhatsApp Inc.",
            date_posted: "2024-01-22",
            date_delais: "2024-02-22",
            offer_status: "close",
            job_type: "Full-time",
            salary: "$89,500",
            pay_period: "year",
            description: "WhatsApp Inc., a leading messaging platform, is seeking a talented Software Engineer to join our Messaging Platform team. As part of the WhatsApp family, you will contribute to building and enhancing one of the most widely used communication platforms globally.\n\nAs a Software Engineer on the Messaging Platform team, you will be involved in designing and implementing features that shape the future of messaging. Join us in creating seamless and secure communication experiences for millions of users worldwide.\n\nResponsibilities:\n- Design, develop, and maintain features for the WhatsApp messaging platform.\n- Collaborate with cross-functional teams to implement scalable and efficient solutions.\n- Optimize performance and troubleshoot issues to ensure a smooth user experience.\n- Stay abreast of industry trends and emerging technologies.\n- Contribute to the overall architecture and design of the messaging platform.\n\nQualifications:\n- Bachelor's degree in Computer Science or a related field.\n- Proven experience as a Software Engineer, with a focus on scalable systems.\n- Proficiency in programming languages such as Java, Kotlin, or C++.\n- Strong understanding of distributed systems and messaging protocols.\n- Experience with mobile application development is a plus.\n\nJoin WhatsApp Inc. and be a part of revolutionizing the way people connect through messaging. If you are passionate about software engineering and excited about shaping the future of communication, we invite you to apply for this exceptional opportunity.\n\nApply now and contribute to the next chapter of innovation at WhatsApp Inc.!",
            country: "United States",
            city: "Menlo Park",
            photo: WhatsApp
        },


        {
            id: 7,
            title: "Customer Service Representative",
            companyName: "McDonald's",
            date_posted: "2024-01-18",
            date_delais: "2024-02-18",
            offer_status: "Open",
            job_type: "Full-time",
            salary: "$15",
            pay_period: "hr",
            description: "Join the McDonald's team as a Customer Service Representative and be a part of the world's leading fast-food restaurant chain. At McDonald's, we are committed to providing exceptional service and creating a positive dining experience for our customers.\n\nAs a Customer Service Representative, you will play a crucial role in ensuring customer satisfaction by taking orders, processing payments, and providing friendly assistance. This position offers a dynamic and fast-paced work environment, making it an ideal opportunity for individuals who thrive in customer-focused roles.\n\nResponsibilities:\n- Greet customers and provide a warm welcome.\n- Take and process customer orders accurately and efficiently.\n- Handle cash transactions and operate the point-of-sale system.\n- Maintain cleanliness and organization in the dining area.\n- Address customer inquiries and resolve issues promptly.\n- Collaborate with team members to ensure smooth operations.\n\nQualifications:\n- Previous experience in customer service is a plus.\n- Excellent communication and interpersonal skills.\n- Ability to work in a fast-paced environment.\n- Flexibility to work various shifts, including evenings and weekends.\n- Enthusiastic and positive attitude.\n\nJoin the McDonald's family and contribute to our commitment to quality, service, and cleanliness. If you are passionate about delivering excellent customer service and enjoy working in a team-oriented atmosphere, we invite you to apply for this exciting opportunity.\n\nApply now and become a valuable member of the McDonald's team!",
            country: "United States",
            city: "New York",
            photo: mac,
        },
        {
            id: 8,
            title: "Technical Support Specialist",
            companyName: "Apple Inc.",
            date_posted: "2024-01-20",
            date_delais: "2024-02-20",
            offer_status: "close",
            job_type: "Full-time",
            salary: "$3000",
            pay_period: "mth",
            description: "Join Apple Inc., a global leader in technology and innovation, as a Technical Support Specialist. At Apple, we are dedicated to creating groundbreaking products and providing unparalleled customer support. As a Technical Support Specialist, you will have the opportunity to be part of a team that ensures our customers receive world-class technical assistance.\n\nResponsibilities:\n- Provide technical support to customers via phone, chat, or email.\n- Diagnose and troubleshoot hardware and software issues on Apple products.\n- Collaborate with cross-functional teams to resolve complex technical problems.\n- Educate customers on the use of Apple products and software.\n- Document and escalate issues as needed.\n- Stay informed about the latest Apple products and technologies.\n\nQualifications:\n- Bachelor's degree in a relevant technical field.\n- Proven experience in technical support or a similar role.\n- Strong knowledge of Apple products, macOS, iOS, and related technologies.\n- Excellent communication and problem-solving skills.\n- Ability to work in a fast-paced and dynamic environment.\n- Apple Certified Support Professional (ACSP) certification is a plus.\n\nJoin the Apple team and be a part of transforming the way people live through innovative technology. If you are passionate about technology, customer service, and making a difference, we encourage you to apply for this exciting opportunity.\n\nApply now and contribute to the legacy of innovation at Apple Inc.!",
            country: "United States",
            city: "Cupertino",
            photo: apple,
        },
        {
            id: 9,
            title: "Software Engineer - Messaging Platform",
            companyName: "WhatsApp Inc.",
            date_posted: "2024-01-22",
            date_delais: "2024-02-22",
            offer_status: "Open",
            job_type: "Full-time",
            salary: "$89,500",
            pay_period: "year",
            description: "WhatsApp Inc., a leading messaging platform, is seeking a talented Software Engineer to join our Messaging Platform team. As part of the WhatsApp family, you will contribute to building and enhancing one of the most widely used communication platforms globally.\n\nAs a Software Engineer on the Messaging Platform team, you will be involved in designing and implementing features that shape the future of messaging. Join us in creating seamless and secure communication experiences for millions of users worldwide.\n\nResponsibilities:\n- Design, develop, and maintain features for the WhatsApp messaging platform.\n- Collaborate with cross-functional teams to implement scalable and efficient solutions.\n- Optimize performance and troubleshoot issues to ensure a smooth user experience.\n- Stay abreast of industry trends and emerging technologies.\n- Contribute to the overall architecture and design of the messaging platform.\n\nQualifications:\n- Bachelor's degree in Computer Science or a related field.\n- Proven experience as a Software Engineer, with a focus on scalable systems.\n- Proficiency in programming languages such as Java, Kotlin, or C++.\n- Strong understanding of distributed systems and messaging protocols.\n- Experience with mobile application development is a plus.\n\nJoin WhatsApp Inc. and be a part of revolutionizing the way people connect through messaging. If you are passionate about software engineering and excited about shaping the future of communication, we invite you to apply for this exceptional opportunity.\n\nApply now and contribute to the next chapter of innovation at WhatsApp Inc.!",
            country: "United States",
            city: "Menlo Park",
            photo: WhatsApp
        },
        {
            id: 10,
            title: "Customer Service Representative",
            companyName: "McDonald's",
            date_posted: "2024-01-18",
            date_delais: "2024-02-18",
            offer_status: "Open",
            job_type: "Full-time",
            salary: "$15",
            pay_period: "hr",
            description: "Join the McDonald's team as a Customer Service Representative and be a part of the world's leading fast-food restaurant chain. At McDonald's, we are committed to providing exceptional service and creating a positive dining experience for our customers.\n\nAs a Customer Service Representative, you will play a crucial role in ensuring customer satisfaction by taking orders, processing payments, and providing friendly assistance. This position offers a dynamic and fast-paced work environment, making it an ideal opportunity for individuals who thrive in customer-focused roles.\n\nResponsibilities:\n- Greet customers and provide a warm welcome.\n- Take and process customer orders accurately and efficiently.\n- Handle cash transactions and operate the point-of-sale system.\n- Maintain cleanliness and organization in the dining area.\n- Address customer inquiries and resolve issues promptly.\n- Collaborate with team members to ensure smooth operations.\n\nQualifications:\n- Previous experience in customer service is a plus.\n- Excellent communication and interpersonal skills.\n- Ability to work in a fast-paced environment.\n- Flexibility to work various shifts, including evenings and weekends.\n- Enthusiastic and positive attitude.\n\nJoin the McDonald's family and contribute to our commitment to quality, service, and cleanliness. If you are passionate about delivering excellent customer service and enjoy working in a team-oriented atmosphere, we invite you to apply for this exciting opportunity.\n\nApply now and become a valuable member of the McDonald's team!",
            country: "United States",
            city: "New York",
            photo: mac,
        },
        {
            id: 11,
            title: "Technical Support Specialist",
            companyName: "Apple Inc.",
            date_posted: "2024-01-20",
            date_delais: "2024-02-20",
            offer_status: "close",
            job_type: "Full-time",
            salary: "$3000",
            pay_period: "mth",
            description: "Join Apple Inc., a global leader in technology and innovation, as a Technical Support Specialist. At Apple, we are dedicated to creating groundbreaking products and providing unparalleled customer support. As a Technical Support Specialist, you will have the opportunity to be part of a team that ensures our customers receive world-class technical assistance.\n\nResponsibilities:\n- Provide technical support to customers via phone, chat, or email.\n- Diagnose and troubleshoot hardware and software issues on Apple products.\n- Collaborate with cross-functional teams to resolve complex technical problems.\n- Educate customers on the use of Apple products and software.\n- Document and escalate issues as needed.\n- Stay informed about the latest Apple products and technologies.\n\nQualifications:\n- Bachelor's degree in a relevant technical field.\n- Proven experience in technical support or a similar role.\n- Strong knowledge of Apple products, macOS, iOS, and related technologies.\n- Excellent communication and problem-solving skills.\n- Ability to work in a fast-paced and dynamic environment.\n- Apple Certified Support Professional (ACSP) certification is a plus.\n\nJoin the Apple team and be a part of transforming the way people live through innovative technology. If you are passionate about technology, customer service, and making a difference, we encourage you to apply for this exciting opportunity.\n\nApply now and contribute to the legacy of innovation at Apple Inc.!",
            country: "United States",
            city: "Cupertino",
            photo: apple,
        },
        {
            id: 12,
            title: "Software Engineer - Messaging Platform",
            companyName: "WhatsApp Inc.",
            date_posted: "2024-01-22",
            date_delais: "2024-02-22",
            offer_status: "close",
            job_type: "Full-time",
            salary: "$89,500",
            pay_period: "year",
            description: "WhatsApp Inc., a leading messaging platform, is seeking a talented Software Engineer to join our Messaging Platform team. As part of the WhatsApp family, you will contribute to building and enhancing one of the most widely used communication platforms globally.\n\nAs a Software Engineer on the Messaging Platform team, you will be involved in designing and implementing features that shape the future of messaging. Join us in creating seamless and secure communication experiences for millions of users worldwide.\n\nResponsibilities:\n- Design, develop, and maintain features for the WhatsApp messaging platform.\n- Collaborate with cross-functional teams to implement scalable and efficient solutions.\n- Optimize performance and troubleshoot issues to ensure a smooth user experience.\n- Stay abreast of industry trends and emerging technologies.\n- Contribute to the overall architecture and design of the messaging platform.\n\nQualifications:\n- Bachelor's degree in Computer Science or a related field.\n- Proven experience as a Software Engineer, with a focus on scalable systems.\n- Proficiency in programming languages such as Java, Kotlin, or C++.\n- Strong understanding of distributed systems and messaging protocols.\n- Experience with mobile application development is a plus.\n\nJoin WhatsApp Inc. and be a part of revolutionizing the way people connect through messaging. If you are passionate about software engineering and excited about shaping the future of communication, we invite you to apply for this exceptional opportunity.\n\nApply now and contribute to the next chapter of innovation at WhatsApp Inc.!",
            country: "United States",
            city: "Menlo Park",
            photo: WhatsApp
        },
        {
            id: 13,
            title: "Technical Support Specialist",
            companyName: "Apple Inc.",
            date_posted: "2024-01-20",
            date_delais: "2024-02-20",
            offer_status: "Open",
            job_type: "Full-time",
            salary: "$3000",
            pay_period: "mth",
            description: "Join Apple Inc., a global leader in technology and innovation, as a Technical Support Specialist. At Apple, we are dedicated to creating groundbreaking products and providing unparalleled customer support. As a Technical Support Specialist, you will have the opportunity to be part of a team that ensures our customers receive world-class technical assistance.\n\nResponsibilities:\n- Provide technical support to customers via phone, chat, or email.\n- Diagnose and troubleshoot hardware and software issues on Apple products.\n- Collaborate with cross-functional teams to resolve complex technical problems.\n- Educate customers on the use of Apple products and software.\n- Document and escalate issues as needed.\n- Stay informed about the latest Apple products and technologies.\n\nQualifications:\n- Bachelor's degree in a relevant technical field.\n- Proven experience in technical support or a similar role.\n- Strong knowledge of Apple products, macOS, iOS, and related technologies.\n- Excellent communication and problem-solving skills.\n- Ability to work in a fast-paced and dynamic environment.\n- Apple Certified Support Professional (ACSP) certification is a plus.\n\nJoin the Apple team and be a part of transforming the way people live through innovative technology. If you are passionate about technology, customer service, and making a difference, we encourage you to apply for this exciting opportunity.\n\nApply now and contribute to the legacy of innovation at Apple Inc.!",
            country: "United States",
            city: "Cupertino",
            photo: apple,
        },

        {
            id: 14,
            title: "Customer Service Representative",
            companyName: "McDonald's",
            date_posted: "2024-01-18",
            date_delais: "2024-02-18",
            offer_status: "Open",
            job_type: "Full-time",
            salary: "$15",
            pay_period: "hr",
            description: "Join the McDonald's team as a Customer Service Representative and be a part of the world's leading fast-food restaurant chain. At McDonald's, we are committed to providing exceptional service and creating a positive dining experience for our customers.\n\nAs a Customer Service Representative, you will play a crucial role in ensuring customer satisfaction by taking orders, processing payments, and providing friendly assistance. This position offers a dynamic and fast-paced work environment, making it an ideal opportunity for individuals who thrive in customer-focused roles.\n\nResponsibilities:\n- Greet customers and provide a warm welcome.\n- Take and process customer orders accurately and efficiently.\n- Handle cash transactions and operate the point-of-sale system.\n- Maintain cleanliness and organization in the dining area.\n- Address customer inquiries and resolve issues promptly.\n- Collaborate with team members to ensure smooth operations.\n\nQualifications:\n- Previous experience in customer service is a plus.\n- Excellent communication and interpersonal skills.\n- Ability to work in a fast-paced environment.\n- Flexibility to work various shifts, including evenings and weekends.\n- Enthusiastic and positive attitude.\n\nJoin the McDonald's family and contribute to our commitment to quality, service, and cleanliness. If you are passionate about delivering excellent customer service and enjoy working in a team-oriented atmosphere, we invite you to apply for this exciting opportunity.\n\nApply now and become a valuable member of the McDonald's team!",
            country: "United States",
            city: "New York",
            photo: mac,
        },
        {
            id: 15,
            title: "Software Engineer - Messaging Platform",
            companyName: "WhatsApp Inc.",
            date_posted: "2024-01-22",
            date_delais: "2024-02-22",
            offer_status: "close",
            job_type: "Full-time",
            salary: "$89,500",
            pay_period: "year",
            description: "WhatsApp Inc., a leading messaging platform, is seeking a talented Software Engineer to join our Messaging Platform team. As part of the WhatsApp family, you will contribute to building and enhancing one of the most widely used communication platforms globally.\n\nAs a Software Engineer on the Messaging Platform team, you will be involved in designing and implementing features that shape the future of messaging. Join us in creating seamless and secure communication experiences for millions of users worldwide.\n\nResponsibilities:\n- Design, develop, and maintain features for the WhatsApp messaging platform.\n- Collaborate with cross-functional teams to implement scalable and efficient solutions.\n- Optimize performance and troubleshoot issues to ensure a smooth user experience.\n- Stay abreast of industry trends and emerging technologies.\n- Contribute to the overall architecture and design of the messaging platform.\n\nQualifications:\n- Bachelor's degree in Computer Science or a related field.\n- Proven experience as a Software Engineer, with a focus on scalable systems.\n- Proficiency in programming languages such as Java, Kotlin, or C++.\n- Strong understanding of distributed systems and messaging protocols.\n- Experience with mobile application development is a plus.\n\nJoin WhatsApp Inc. and be a part of revolutionizing the way people connect through messaging. If you are passionate about software engineering and excited about shaping the future of communication, we invite you to apply for this exceptional opportunity.\n\nApply now and contribute to the next chapter of innovation at WhatsApp Inc.!",
            country: "United States",
            city: "Menlo Park",
            photo: WhatsApp
        },


        {
            id: 16,
            title: "Customer Service Representative",
            companyName: "McDonald's",
            date_posted: "2024-01-18",
            date_delais: "2024-02-18",
            offer_status: "Open",
            job_type: "Full-time",
            salary: "$15",
            pay_period: "hr",
            description: "Join the McDonald's team as a Customer Service Representative and be a part of the world's leading fast-food restaurant chain. At McDonald's, we are committed to providing exceptional service and creating a positive dining experience for our customers.\n\nAs a Customer Service Representative, you will play a crucial role in ensuring customer satisfaction by taking orders, processing payments, and providing friendly assistance. This position offers a dynamic and fast-paced work environment, making it an ideal opportunity for individuals who thrive in customer-focused roles.\n\nResponsibilities:\n- Greet customers and provide a warm welcome.\n- Take and process customer orders accurately and efficiently.\n- Handle cash transactions and operate the point-of-sale system.\n- Maintain cleanliness and organization in the dining area.\n- Address customer inquiries and resolve issues promptly.\n- Collaborate with team members to ensure smooth operations.\n\nQualifications:\n- Previous experience in customer service is a plus.\n- Excellent communication and interpersonal skills.\n- Ability to work in a fast-paced environment.\n- Flexibility to work various shifts, including evenings and weekends.\n- Enthusiastic and positive attitude.\n\nJoin the McDonald's family and contribute to our commitment to quality, service, and cleanliness. If you are passionate about delivering excellent customer service and enjoy working in a team-oriented atmosphere, we invite you to apply for this exciting opportunity.\n\nApply now and become a valuable member of the McDonald's team!",
            country: "United States",
            city: "New York",
            photo: mac,
        },
        {
            id: 17,
            title: "Technical Support Specialist",
            companyName: "Apple Inc.",
            date_posted: "2024-01-20",
            date_delais: "2024-02-20",
            offer_status: "close",
            job_type: "Full-time",
            salary: "$3000",
            pay_period: "mth",
            description: "Join Apple Inc., a global leader in technology and innovation, as a Technical Support Specialist. At Apple, we are dedicated to creating groundbreaking products and providing unparalleled customer support. As a Technical Support Specialist, you will have the opportunity to be part of a team that ensures our customers receive world-class technical assistance.\n\nResponsibilities:\n- Provide technical support to customers via phone, chat, or email.\n- Diagnose and troubleshoot hardware and software issues on Apple products.\n- Collaborate with cross-functional teams to resolve complex technical problems.\n- Educate customers on the use of Apple products and software.\n- Document and escalate issues as needed.\n- Stay informed about the latest Apple products and technologies.\n\nQualifications:\n- Bachelor's degree in a relevant technical field.\n- Proven experience in technical support or a similar role.\n- Strong knowledge of Apple products, macOS, iOS, and related technologies.\n- Excellent communication and problem-solving skills.\n- Ability to work in a fast-paced and dynamic environment.\n- Apple Certified Support Professional (ACSP) certification is a plus.\n\nJoin the Apple team and be a part of transforming the way people live through innovative technology. If you are passionate about technology, customer service, and making a difference, we encourage you to apply for this exciting opportunity.\n\nApply now and contribute to the legacy of innovation at Apple Inc.!",
            country: "United States",
            city: "Cupertino",
            photo: apple,
        },
        {
            id: 18,
            title: "Software Engineer - Messaging Platform",
            companyName: "WhatsApp Inc.",
            date_posted: "2024-01-22",
            date_delais: "2024-02-22",
            offer_status: "Open",
            job_type: "Full-time",
            salary: "$89,500",
            pay_period: "year",
            description: "WhatsApp Inc., a leading messaging platform, is seeking a talented Software Engineer to join our Messaging Platform team. As part of the WhatsApp family, you will contribute to building and enhancing one of the most widely used communication platforms globally.\n\nAs a Software Engineer on the Messaging Platform team, you will be involved in designing and implementing features that shape the future of messaging. Join us in creating seamless and secure communication experiences for millions of users worldwide.\n\nResponsibilities:\n- Design, develop, and maintain features for the WhatsApp messaging platform.\n- Collaborate with cross-functional teams to implement scalable and efficient solutions.\n- Optimize performance and troubleshoot issues to ensure a smooth user experience.\n- Stay abreast of industry trends and emerging technologies.\n- Contribute to the overall architecture and design of the messaging platform.\n\nQualifications:\n- Bachelor's degree in Computer Science or a related field.\n- Proven experience as a Software Engineer, with a focus on scalable systems.\n- Proficiency in programming languages such as Java, Kotlin, or C++.\n- Strong understanding of distributed systems and messaging protocols.\n- Experience with mobile application development is a plus.\n\nJoin WhatsApp Inc. and be a part of revolutionizing the way people connect through messaging. If you are passionate about software engineering and excited about shaping the future of communication, we invite you to apply for this exceptional opportunity.\n\nApply now and contribute to the next chapter of innovation at WhatsApp Inc.!",
            country: "United States",
            city: "Menlo Park",
            photo: WhatsApp
        },
        {
            id: 19,
            title: "Customer Service Representative",
            companyName: "McDonald's",
            date_posted: "2024-01-18",
            date_delais: "2024-02-18",
            offer_status: "Open",
            job_type: "Full-time",
            salary: "$15",
            pay_period: "hr",
            description: "Join the McDonald's team as a Customer Service Representative and be a part of the world's leading fast-food restaurant chain. At McDonald's, we are committed to providing exceptional service and creating a positive dining experience for our customers.\n\nAs a Customer Service Representative, you will play a crucial role in ensuring customer satisfaction by taking orders, processing payments, and providing friendly assistance. This position offers a dynamic and fast-paced work environment, making it an ideal opportunity for individuals who thrive in customer-focused roles.\n\nResponsibilities:\n- Greet customers and provide a warm welcome.\n- Take and process customer orders accurately and efficiently.\n- Handle cash transactions and operate the point-of-sale system.\n- Maintain cleanliness and organization in the dining area.\n- Address customer inquiries and resolve issues promptly.\n- Collaborate with team members to ensure smooth operations.\n\nQualifications:\n- Previous experience in customer service is a plus.\n- Excellent communication and interpersonal skills.\n- Ability to work in a fast-paced environment.\n- Flexibility to work various shifts, including evenings and weekends.\n- Enthusiastic and positive attitude.\n\nJoin the McDonald's family and contribute to our commitment to quality, service, and cleanliness. If you are passionate about delivering excellent customer service and enjoy working in a team-oriented atmosphere, we invite you to apply for this exciting opportunity.\n\nApply now and become a valuable member of the McDonald's team!",
            country: "United States",
            city: "New York",
            photo: mac,
        },
        {
            id: 20,
            title: "Technical Support Specialist",
            companyName: "Apple Inc.",
            date_posted: "2024-01-20",
            date_delais: "2024-02-20",
            offer_status: "close",
            job_type: "Full-time",
            salary: "$3000",
            pay_period: "mth",
            description: "Join Apple Inc., a global leader in technology and innovation, as a Technical Support Specialist. At Apple, we are dedicated to creating groundbreaking products and providing unparalleled customer support. As a Technical Support Specialist, you will have the opportunity to be part of a team that ensures our customers receive world-class technical assistance.\n\nResponsibilities:\n- Provide technical support to customers via phone, chat, or email.\n- Diagnose and troubleshoot hardware and software issues on Apple products.\n- Collaborate with cross-functional teams to resolve complex technical problems.\n- Educate customers on the use of Apple products and software.\n- Document and escalate issues as needed.\n- Stay informed about the latest Apple products and technologies.\n\nQualifications:\n- Bachelor's degree in a relevant technical field.\n- Proven experience in technical support or a similar role.\n- Strong knowledge of Apple products, macOS, iOS, and related technologies.\n- Excellent communication and problem-solving skills.\n- Ability to work in a fast-paced and dynamic environment.\n- Apple Certified Support Professional (ACSP) certification is a plus.\n\nJoin the Apple team and be a part of transforming the way people live through innovative technology. If you are passionate about technology, customer service, and making a difference, we encourage you to apply for this exciting opportunity.\n\nApply now and contribute to the legacy of innovation at Apple Inc.!",
            country: "United States",
            city: "Cupertino",
            photo: apple,
        },
        {
            id: 21,
            title: "Software Engineer - Messaging Platform",
            companyName: "WhatsApp Inc.",
            date_posted: "2024-01-22",
            date_delais: "2024-02-22",
            offer_status: "close",
            job_type: "Full-time",
            salary: "$89,500",
            pay_period: "year",
            description: "WhatsApp Inc., a leading messaging platform, is seeking a talented Software Engineer to join our Messaging Platform team. As part of the WhatsApp family, you will contribute to building and enhancing one of the most widely used communication platforms globally.\n\nAs a Software Engineer on the Messaging Platform team, you will be involved in designing and implementing features that shape the future of messaging. Join us in creating seamless and secure communication experiences for millions of users worldwide.\n\nResponsibilities:\n- Design, develop, and maintain features for the WhatsApp messaging platform.\n- Collaborate with cross-functional teams to implement scalable and efficient solutions.\n- Optimize performance and troubleshoot issues to ensure a smooth user experience.\n- Stay abreast of industry trends and emerging technologies.\n- Contribute to the overall architecture and design of the messaging platform.\n\nQualifications:\n- Bachelor's degree in Computer Science or a related field.\n- Proven experience as a Software Engineer, with a focus on scalable systems.\n- Proficiency in programming languages such as Java, Kotlin, or C++.\n- Strong understanding of distributed systems and messaging protocols.\n- Experience with mobile application development is a plus.\n\nJoin WhatsApp Inc. and be a part of revolutionizing the way people connect through messaging. If you are passionate about software engineering and excited about shaping the future of communication, we invite you to apply for this exceptional opportunity.\n\nApply now and contribute to the next chapter of innovation at WhatsApp Inc.!",
            country: "United States",
            city: "Menlo Park",
            photo: WhatsApp
        },
        {
            id: 22,
            title: "Technical Support Specialist",
            companyName: "Apple Inc.",
            date_posted: "2024-01-20",
            date_delais: "2024-02-20",
            offer_status: "Open",
            job_type: "Full-time",
            salary: "$3000",
            pay_period: "mth",
            description: "Join Apple Inc., a global leader in technology and innovation, as a Technical Support Specialist. At Apple, we are dedicated to creating groundbreaking products and providing unparalleled customer support. As a Technical Support Specialist, you will have the opportunity to be part of a team that ensures our customers receive world-class technical assistance.\n\nResponsibilities:\n- Provide technical support to customers via phone, chat, or email.\n- Diagnose and troubleshoot hardware and software issues on Apple products.\n- Collaborate with cross-functional teams to resolve complex technical problems.\n- Educate customers on the use of Apple products and software.\n- Document and escalate issues as needed.\n- Stay informed about the latest Apple products and technologies.\n\nQualifications:\n- Bachelor's degree in a relevant technical field.\n- Proven experience in technical support or a similar role.\n- Strong knowledge of Apple products, macOS, iOS, and related technologies.\n- Excellent communication and problem-solving skills.\n- Ability to work in a fast-paced and dynamic environment.\n- Apple Certified Support Professional (ACSP) certification is a plus.\n\nJoin the Apple team and be a part of transforming the way people live through innovative technology. If you are passionate about technology, customer service, and making a difference, we encourage you to apply for this exciting opportunity.\n\nApply now and contribute to the legacy of innovation at Apple Inc.!",
            country: "United States",
            city: "Cupertino",
            photo: apple,
        },

        {
            id: 23,
            title: "Customer Service Representative",
            companyName: "McDonald's",
            date_posted: "2024-01-18",
            date_delais: "2024-02-18",
            offer_status: "Open",
            job_type: "Full-time",
            salary: "$15",
            pay_period: "hr",
            description: "Join the McDonald's team as a Customer Service Representative and be a part of the world's leading fast-food restaurant chain. At McDonald's, we are committed to providing exceptional service and creating a positive dining experience for our customers.\n\nAs a Customer Service Representative, you will play a crucial role in ensuring customer satisfaction by taking orders, processing payments, and providing friendly assistance. This position offers a dynamic and fast-paced work environment, making it an ideal opportunity for individuals who thrive in customer-focused roles.\n\nResponsibilities:\n- Greet customers and provide a warm welcome.\n- Take and process customer orders accurately and efficiently.\n- Handle cash transactions and operate the point-of-sale system.\n- Maintain cleanliness and organization in the dining area.\n- Address customer inquiries and resolve issues promptly.\n- Collaborate with team members to ensure smooth operations.\n\nQualifications:\n- Previous experience in customer service is a plus.\n- Excellent communication and interpersonal skills.\n- Ability to work in a fast-paced environment.\n- Flexibility to work various shifts, including evenings and weekends.\n- Enthusiastic and positive attitude.\n\nJoin the McDonald's family and contribute to our commitment to quality, service, and cleanliness. If you are passionate about delivering excellent customer service and enjoy working in a team-oriented atmosphere, we invite you to apply for this exciting opportunity.\n\nApply now and become a valuable member of the McDonald's team!",
            country: "United States",
            city: "New York",
            photo: mac,
        },
        {
            id: 24,
            title: "Software Engineer - Messaging Platform",
            companyName: "WhatsApp Inc.",
            date_posted: "2024-01-22",
            date_delais: "2024-02-22",
            offer_status: "close",
            job_type: "Full-time",
            salary: "$89,500",
            pay_period: "year",
            description: "WhatsApp Inc., a leading messaging platform, is seeking a talented Software Engineer to join our Messaging Platform team. As part of the WhatsApp family, you will contribute to building and enhancing one of the most widely used communication platforms globally.\n\nAs a Software Engineer on the Messaging Platform team, you will be involved in designing and implementing features that shape the future of messaging. Join us in creating seamless and secure communication experiences for millions of users worldwide.\n\nResponsibilities:\n- Design, develop, and maintain features for the WhatsApp messaging platform.\n- Collaborate with cross-functional teams to implement scalable and efficient solutions.\n- Optimize performance and troubleshoot issues to ensure a smooth user experience.\n- Stay abreast of industry trends and emerging technologies.\n- Contribute to the overall architecture and design of the messaging platform.\n\nQualifications:\n- Bachelor's degree in Computer Science or a related field.\n- Proven experience as a Software Engineer, with a focus on scalable systems.\n- Proficiency in programming languages such as Java, Kotlin, or C++.\n- Strong understanding of distributed systems and messaging protocols.\n- Experience with mobile application development is a plus.\n\nJoin WhatsApp Inc. and be a part of revolutionizing the way people connect through messaging. If you are passionate about software engineering and excited about shaping the future of communication, we invite you to apply for this exceptional opportunity.\n\nApply now and contribute to the next chapter of innovation at WhatsApp Inc.!",
            country: "United States",
            city: "Menlo Park",
            photo: WhatsApp
        },


        {
            id: 25,
            title: "Customer Service Representative",
            companyName: "McDonald's",
            date_posted: "2024-01-18",
            date_delais: "2024-02-18",
            offer_status: "Open",
            job_type: "Full-time",
            salary: "$15",
            pay_period: "hr",
            description: "Join the McDonald's team as a Customer Service Representative and be a part of the world's leading fast-food restaurant chain. At McDonald's, we are committed to providing exceptional service and creating a positive dining experience for our customers.\n\nAs a Customer Service Representative, you will play a crucial role in ensuring customer satisfaction by taking orders, processing payments, and providing friendly assistance. This position offers a dynamic and fast-paced work environment, making it an ideal opportunity for individuals who thrive in customer-focused roles.\n\nResponsibilities:\n- Greet customers and provide a warm welcome.\n- Take and process customer orders accurately and efficiently.\n- Handle cash transactions and operate the point-of-sale system.\n- Maintain cleanliness and organization in the dining area.\n- Address customer inquiries and resolve issues promptly.\n- Collaborate with team members to ensure smooth operations.\n\nQualifications:\n- Previous experience in customer service is a plus.\n- Excellent communication and interpersonal skills.\n- Ability to work in a fast-paced environment.\n- Flexibility to work various shifts, including evenings and weekends.\n- Enthusiastic and positive attitude.\n\nJoin the McDonald's family and contribute to our commitment to quality, service, and cleanliness. If you are passionate about delivering excellent customer service and enjoy working in a team-oriented atmosphere, we invite you to apply for this exciting opportunity.\n\nApply now and become a valuable member of the McDonald's team!",
            country: "United States",
            city: "New York",
            photo: mac,
        },
        {
            id: 26,
            title: "Technical Support Specialist",
            companyName: "Apple Inc.",
            date_posted: "2024-01-20",
            date_delais: "2024-02-20",
            offer_status: "close",
            job_type: "Full-time",
            salary: "$3000",
            pay_period: "mth",
            description: "Join Apple Inc., a global leader in technology and innovation, as a Technical Support Specialist. At Apple, we are dedicated to creating groundbreaking products and providing unparalleled customer support. As a Technical Support Specialist, you will have the opportunity to be part of a team that ensures our customers receive world-class technical assistance.\n\nResponsibilities:\n- Provide technical support to customers via phone, chat, or email.\n- Diagnose and troubleshoot hardware and software issues on Apple products.\n- Collaborate with cross-functional teams to resolve complex technical problems.\n- Educate customers on the use of Apple products and software.\n- Document and escalate issues as needed.\n- Stay informed about the latest Apple products and technologies.\n\nQualifications:\n- Bachelor's degree in a relevant technical field.\n- Proven experience in technical support or a similar role.\n- Strong knowledge of Apple products, macOS, iOS, and related technologies.\n- Excellent communication and problem-solving skills.\n- Ability to work in a fast-paced and dynamic environment.\n- Apple Certified Support Professional (ACSP) certification is a plus.\n\nJoin the Apple team and be a part of transforming the way people live through innovative technology. If you are passionate about technology, customer service, and making a difference, we encourage you to apply for this exciting opportunity.\n\nApply now and contribute to the legacy of innovation at Apple Inc.!",
            country: "United States",
            city: "Cupertino",
            photo: apple,
        },
        {
            id: 27,
            title: "Software Engineer - Messaging Platform",
            companyName: "WhatsApp Inc.",
            date_posted: "2024-01-22",
            date_delais: "2024-02-22",
            offer_status: "Open",
            job_type: "Full-time",
            salary: "$89,500",
            pay_period: "year",
            description: "WhatsApp Inc., a leading messaging platform, is seeking a talented Software Engineer to join our Messaging Platform team. As part of the WhatsApp family, you will contribute to building and enhancing one of the most widely used communication platforms globally.\n\nAs a Software Engineer on the Messaging Platform team, you will be involved in designing and implementing features that shape the future of messaging. Join us in creating seamless and secure communication experiences for millions of users worldwide.\n\nResponsibilities:\n- Design, develop, and maintain features for the WhatsApp messaging platform.\n- Collaborate with cross-functional teams to implement scalable and efficient solutions.\n- Optimize performance and troubleshoot issues to ensure a smooth user experience.\n- Stay abreast of industry trends and emerging technologies.\n- Contribute to the overall architecture and design of the messaging platform.\n\nQualifications:\n- Bachelor's degree in Computer Science or a related field.\n- Proven experience as a Software Engineer, with a focus on scalable systems.\n- Proficiency in programming languages such as Java, Kotlin, or C++.\n- Strong understanding of distributed systems and messaging protocols.\n- Experience with mobile application development is a plus.\n\nJoin WhatsApp Inc. and be a part of revolutionizing the way people connect through messaging. If you are passionate about software engineering and excited about shaping the future of communication, we invite you to apply for this exceptional opportunity.\n\nApply now and contribute to the next chapter of innovation at WhatsApp Inc.!",
            country: "United States",
            city: "Menlo Park",
            photo: WhatsApp
        }
    ]
    return (
        <div className='flex flex-col gap-8 my-6 mx-2'>
            {jobs.map(job => (
                <JobCard job={job}/>
            ))}
        </div>
    )
}

export default CompanyJobOffers